(function (dateFormat, undefined) {
    "use strict";

	dateFormat.jqplot = {
        "day-of-month-1": "%#d",
        "day-of-month-2": "%d",
        "day-of-week-abbr": "%a",
        "day-of-week": "%A",
        "month-1": "%#m",
        "month-2": "%m",
        "month-name-abbr": "%b",
        "month-name": "%B",
        "year-2": "%y",
        "year-3": "%Y",
        "year-4": "%Y",
        "am-pm-2": "%p",
        "am-pm-1": "%p",
        "time-24h-1": "%#h",
        "time-24h-2": "%H",
        "time-12h-1": "%#I",
        "time-12h-2": "%I",
        "minutes-1": "%#M",
        "minutes-2": "%M",
        "seconds-1": "%#S",
        "seconds-2": "%S",
        "deciseconds-optional": "%#N",
        "centiseconds-optional": "%N",
        "milliseconds-optional": "%N",
        "microseconds-optional": "%N",
        "nanoseconds-optional": "%N",
        "picoseconds-optional": "%N",
        "femtoseconds-optional": "%N",
        "deciseconds": "%#N",
        "centiseconds": "%N",
        "milliseconds": "%N",
        "microseconds": "%N",
        "nanoseconds": "%N",
        "picoseconds": "%N",
        "femtoseconds": "%N",
        "timezone-1": "%G",
        "timezone-2": "%G",
        "timezone-3": "%G"
    };

}(window.dateFormat));